"""教育部双一流建设高校名单（147所）及官网。"""

from dataclasses import dataclass, field


@dataclass
class DoubleFirstClassUni:
    name: str
    url: str
    province: str
    tags: list[str] = field(default_factory=list)


PROVINCE_TO_REGION = {
    "北京": "华北", "天津": "华北", "河北": "华北", "山西": "华北", "内蒙古": "华北",
    "辽宁": "东北", "吉林": "东北", "黑龙江": "东北",
    "上海": "华东", "江苏": "华东", "浙江": "华东", "安徽": "华东",
    "福建": "华东", "江西": "华东", "山东": "华东",
    "河南": "华中", "湖北": "华中", "湖南": "华中",
    "广东": "华南", "广西": "华南", "海南": "华南",
    "重庆": "西南", "四川": "西南", "贵州": "西南", "云南": "西南", "西藏": "西南",
    "陕西": "西北", "甘肃": "西北", "青海": "西北", "宁夏": "西北", "新疆": "西北",
    "其他": "其他",
}

# (name, url, province, tags_csv)
_RAW = [
    ("北京大学", "https://www.pku.edu.cn", "北京", "985,211,双一流"),
    ("中国人民大学", "https://www.ruc.edu.cn", "北京", "985,211,双一流"),
    ("清华大学", "https://www.tsinghua.edu.cn", "北京", "985,211,双一流"),
    ("北京航空航天大学", "https://www.buaa.edu.cn", "北京", "985,211,双一流"),
    ("北京理工大学", "https://www.bit.edu.cn", "北京", "985,211,双一流"),
    ("中国农业大学", "https://www.cau.edu.cn", "北京", "985,211,双一流"),
    ("北京师范大学", "https://www.bnu.edu.cn", "北京", "985,211,双一流"),
    ("中央民族大学", "https://www.muc.edu.cn", "北京", "985,211,双一流"),
    ("北京交通大学", "https://www.bjtu.edu.cn", "北京", "211,双一流"),
    ("北京工业大学", "https://www.bjut.edu.cn", "北京", "211,双一流"),
    ("北京科技大学", "https://www.ustb.edu.cn", "北京", "211,双一流"),
    ("北京化工大学", "https://www.buct.edu.cn", "北京", "211,双一流"),
    ("北京邮电大学", "https://www.bupt.edu.cn", "北京", "211,双一流"),
    ("北京林业大学", "https://www.bjfu.edu.cn", "北京", "211,双一流"),
    ("北京协和医学院", "https://www.pumc.edu.cn", "北京", "211,双一流"),
    ("北京中医药大学", "https://www.bucm.edu.cn", "北京", "211,双一流"),
    ("北京外国语大学", "https://www.bfsu.edu.cn", "北京", "211,双一流"),
    ("中国传媒大学", "https://www.cuc.edu.cn", "北京", "211,双一流"),
    ("中央财经大学", "https://www.cufe.edu.cn", "北京", "211,双一流"),
    ("对外经济贸易大学", "https://www.uibe.edu.cn", "北京", "211,双一流"),
    ("北京体育大学", "https://www.bsu.edu.cn", "北京", "211,双一流"),
    ("中央音乐学院", "https://www.ccom.edu.cn", "北京", "211,双一流"),
    ("中国政法大学", "https://www.cupl.edu.cn", "北京", "211,双一流"),
    ("华北电力大学", "https://www.ncepu.edu.cn", "北京", "211,双一流"),
    ("中国矿业大学（北京）", "https://www.cumtb.edu.cn", "北京", "211,双一流"),
    ("中国石油大学（北京）", "https://www.cup.edu.cn", "北京", "211,双一流"),
    ("中国地质大学（北京）", "https://www.cugb.edu.cn", "北京", "211,双一流"),
    ("中国科学院大学", "https://www.ucas.edu.cn", "北京", "双一流"),
    ("首都师范大学", "https://www.cnu.edu.cn", "北京", "双一流"),
    ("外交学院", "https://www.cfau.edu.cn", "北京", "双一流"),
    ("中国人民公安大学", "https://www.ppsuc.edu.cn", "北京", "双一流"),
    ("中国音乐学院", "https://www.ccmusic.edu.cn", "北京", "双一流"),
    ("中央美术学院", "https://www.cafa.edu.cn", "北京", "双一流"),
    ("中央戏剧学院", "https://www.zhongxi.cn", "北京", "双一流"),
    ("南开大学", "https://www.nankai.edu.cn", "天津", "985,211,双一流"),
    ("天津大学", "https://www.tju.edu.cn", "天津", "985,211,双一流"),
    ("天津医科大学", "https://www.tmu.edu.cn", "天津", "211,双一流"),
    ("天津工业大学", "https://www.tiangong.edu.cn", "天津", "双一流"),
    ("天津中医药大学", "https://www.tjutcm.edu.cn", "天津", "双一流"),
    ("河北工业大学", "https://www.hebut.edu.cn", "河北", "211,双一流"),
    ("山西大学", "https://www.sxu.edu.cn", "山西", "双一流"),
    ("太原理工大学", "https://www.tyut.edu.cn", "山西", "211,双一流"),
    ("内蒙古大学", "https://www.imu.edu.cn", "内蒙古", "211,双一流"),
    ("辽宁大学", "https://www.lnu.edu.cn", "辽宁", "211,双一流"),
    ("大连理工大学", "https://www.dlut.edu.cn", "辽宁", "985,211,双一流"),
    ("东北大学", "https://www.neu.edu.cn", "辽宁", "985,211,双一流"),
    ("大连海事大学", "https://www.dlmu.edu.cn", "辽宁", "211,双一流"),
    ("吉林大学", "https://www.jlu.edu.cn", "吉林", "985,211,双一流"),
    ("延边大学", "https://www.ybu.edu.cn", "吉林", "211,双一流"),
    ("东北师范大学", "https://www.nenu.edu.cn", "吉林", "211,双一流"),
    ("哈尔滨工业大学", "https://www.hit.edu.cn", "黑龙江", "985,211,双一流"),
    ("哈尔滨工程大学", "https://www.hrbeu.edu.cn", "黑龙江", "211,双一流"),
    ("东北林业大学", "https://www.nefu.edu.cn", "黑龙江", "211,双一流"),
    ("东北农业大学", "https://www.neau.edu.cn", "黑龙江", "211,双一流"),
    ("复旦大学", "https://www.fudan.edu.cn", "上海", "985,211,双一流"),
    ("同济大学", "https://www.tongji.edu.cn", "上海", "985,211,双一流"),
    ("上海交通大学", "https://www.sjtu.edu.cn", "上海", "985,211,双一流"),
    ("华东师范大学", "https://www.ecnu.edu.cn", "上海", "985,211,双一流"),
    ("华东理工大学", "https://www.ecust.edu.cn", "上海", "211,双一流"),
    ("东华大学", "https://www.dhu.edu.cn", "上海", "211,双一流"),
    ("上海财经大学", "https://www.shufe.edu.cn", "上海", "211,双一流"),
    ("上海大学", "https://www.shu.edu.cn", "上海", "211,双一流"),
    ("上海外国语大学", "https://www.shisu.edu.cn", "上海", "211,双一流"),
    ("海军军医大学", "https://www.smmu.edu.cn", "上海", "211,双一流"),
    ("上海海洋大学", "https://www.shou.edu.cn", "上海", "双一流"),
    ("上海中医药大学", "https://www.shutcm.edu.cn", "上海", "双一流"),
    ("上海体育大学", "https://www.sus.edu.cn", "上海", "双一流"),
    ("上海音乐学院", "https://www.shcmusic.edu.cn", "上海", "双一流"),
    ("上海科技大学", "https://www.shanghaitech.edu.cn", "上海", "双一流"),
    ("南京大学", "https://www.nju.edu.cn", "江苏", "985,211,双一流"),
    ("东南大学", "https://www.seu.edu.cn", "江苏", "985,211,双一流"),
    ("苏州大学", "https://www.suda.edu.cn", "江苏", "211,双一流"),
    ("南京航空航天大学", "https://www.nuaa.edu.cn", "江苏", "211,双一流"),
    ("南京理工大学", "https://www.njust.edu.cn", "江苏", "211,双一流"),
    ("中国矿业大学", "https://www.cumt.edu.cn", "江苏", "211,双一流"),
    ("河海大学", "https://www.hhu.edu.cn", "江苏", "211,双一流"),
    ("江南大学", "https://www.jiangnan.edu.cn", "江苏", "211,双一流"),
    ("南京农业大学", "https://www.njau.edu.cn", "江苏", "211,双一流"),
    ("中国药科大学", "https://www.cpu.edu.cn", "江苏", "211,双一流"),
    ("南京师范大学", "https://www.njnu.edu.cn", "江苏", "211,双一流"),
    ("南京邮电大学", "https://www.njupt.edu.cn", "江苏", "双一流"),
    ("南京林业大学", "https://www.njfu.edu.cn", "江苏", "双一流"),
    ("南京信息工程大学", "https://www.nuist.edu.cn", "江苏", "双一流"),
    ("南京医科大学", "https://www.njmu.edu.cn", "江苏", "双一流"),
    ("南京中医药大学", "https://www.njucm.edu.cn", "江苏", "双一流"),
    ("浙江大学", "https://www.zju.edu.cn", "浙江", "985,211,双一流"),
    ("中国美术学院", "https://www.caa.edu.cn", "浙江", "双一流"),
    ("宁波大学", "https://www.nbu.edu.cn", "浙江", "双一流"),
    ("安徽大学", "https://www.ahu.edu.cn", "安徽", "211,双一流"),
    ("中国科学技术大学", "https://www.ustc.edu.cn", "安徽", "985,211,双一流"),
    ("合肥工业大学", "https://www.hfut.edu.cn", "安徽", "211,双一流"),
    ("厦门大学", "https://www.xmu.edu.cn", "福建", "985,211,双一流"),
    ("福州大学", "https://www.fzu.edu.cn", "福建", "211,双一流"),
    ("南昌大学", "https://www.ncu.edu.cn", "江西", "211,双一流"),
    ("山东大学", "https://www.sdu.edu.cn", "山东", "985,211,双一流"),
    ("中国海洋大学", "https://www.ouc.edu.cn", "山东", "985,211,双一流"),
    ("中国石油大学（华东）", "https://www.upc.edu.cn", "山东", "211,双一流"),
    ("郑州大学", "https://www.zzu.edu.cn", "河南", "211,双一流"),
    ("河南大学", "https://www.henu.edu.cn", "河南", "双一流"),
    ("武汉大学", "https://www.whu.edu.cn", "湖北", "985,211,双一流"),
    ("华中科技大学", "https://www.hust.edu.cn", "湖北", "985,211,双一流"),
    ("武汉理工大学", "https://www.whut.edu.cn", "湖北", "211,双一流"),
    ("华中农业大学", "https://www.hzau.edu.cn", "湖北", "211,双一流"),
    ("华中师范大学", "https://www.ccnu.edu.cn", "湖北", "211,双一流"),
    ("中南财经政法大学", "https://www.zuel.edu.cn", "湖北", "211,双一流"),
    ("中国地质大学（武汉）", "https://www.cug.edu.cn", "湖北", "211,双一流"),
    ("湖南大学", "https://www.hnu.edu.cn", "湖南", "985,211,双一流"),
    ("中南大学", "https://www.csu.edu.cn", "湖南", "985,211,双一流"),
    ("湘潭大学", "https://www.xtu.edu.cn", "湖南", "双一流"),
    ("湖南师范大学", "https://www.hunnu.edu.cn", "湖南", "211,双一流"),
    ("中山大学", "https://www.sysu.edu.cn", "广东", "985,211,双一流"),
    ("华南理工大学", "https://www.scut.edu.cn", "广东", "985,211,双一流"),
    ("暨南大学", "https://www.jnu.edu.cn", "广东", "211,双一流"),
    ("广州中医药大学", "https://www.gzucm.edu.cn", "广东", "双一流"),
    ("华南农业大学", "https://www.scau.edu.cn", "广东", "双一流"),
    ("广州医科大学", "https://www.gzhmu.edu.cn", "广东", "双一流"),
    ("华南师范大学", "https://www.scnu.edu.cn", "广东", "211,双一流"),
    ("南方科技大学", "https://www.sustech.edu.cn", "广东", "双一流"),
    ("广西大学", "https://www.gxu.edu.cn", "广西", "211,双一流"),
    ("海南大学", "https://www.hainanu.edu.cn", "海南", "211,双一流"),
    ("四川大学", "https://www.scu.edu.cn", "四川", "985,211,双一流"),
    ("电子科技大学", "https://www.uestc.edu.cn", "四川", "985,211,双一流"),
    ("西南交通大学", "https://www.swjtu.edu.cn", "四川", "211,双一流"),
    ("西南石油大学", "https://www.swpu.edu.cn", "四川", "双一流"),
    ("成都理工大学", "https://www.cdut.edu.cn", "四川", "双一流"),
    ("四川农业大学", "https://www.sicau.edu.cn", "四川", "211,双一流"),
    ("成都中医药大学", "https://www.cdutcm.edu.cn", "四川", "双一流"),
    ("西南财经大学", "https://www.swufe.edu.cn", "四川", "211,双一流"),
    ("重庆大学", "https://www.cqu.edu.cn", "重庆", "985,211,双一流"),
    ("西南大学", "https://www.swu.edu.cn", "重庆", "211,双一流"),
    ("贵州大学", "https://www.gzu.edu.cn", "贵州", "211,双一流"),
    ("云南大学", "https://www.ynu.edu.cn", "云南", "211,双一流"),
    ("西藏大学", "https://www.utibet.edu.cn", "西藏", "211,双一流"),
    ("西安交通大学", "https://www.xjtu.edu.cn", "陕西", "985,211,双一流"),
    ("西北工业大学", "https://www.nwpu.edu.cn", "陕西", "985,211,双一流"),
    ("西北农林科技大学", "https://www.nwafu.edu.cn", "陕西", "985,211,双一流"),
    ("西安电子科技大学", "https://www.xidian.edu.cn", "陕西", "211,双一流"),
    ("长安大学", "https://www.chd.edu.cn", "陕西", "211,双一流"),
    ("西北大学", "https://www.nwu.edu.cn", "陕西", "211,双一流"),
    ("陕西师范大学", "https://www.snnu.edu.cn", "陕西", "211,双一流"),
    ("空军军医大学", "https://www.fmmu.edu.cn", "陕西", "211,双一流"),
    ("兰州大学", "https://www.lzu.edu.cn", "甘肃", "985,211,双一流"),
    ("青海大学", "https://www.qhu.edu.cn", "青海", "211,双一流"),
    ("宁夏大学", "https://www.nxu.edu.cn", "宁夏", "211,双一流"),
    ("新疆大学", "https://www.xju.edu.cn", "新疆", "211,双一流"),
    ("石河子大学", "https://www.shzu.edu.cn", "新疆", "211,双一流"),
    ("国防科技大学", "https://www.nudt.edu.cn", "其他", "985,211,双一流"),
]

DOUBLE_FIRST_CLASS_UNIVERSITIES: list[DoubleFirstClassUni] = [
    DoubleFirstClassUni(name, url, prov, tags.split(",") if tags else [])
    for name, url, prov, tags in _RAW
]
