"""147所双一流高校外语/法学学院官方子站（权威来源，2026-06）。"""

from dataclasses import dataclass, field

from double_first_class import DOUBLE_FIRST_CLASS_UNIVERSITIES

PROVINCE_BY_UNI = {u.name: u.province for u in DOUBLE_FIRST_CLASS_UNIVERSITIES}
TAGS_BY_UNI = {u.name: u.tags for u in DOUBLE_FIRST_CLASS_UNIVERSITIES}


@dataclass
class OfficialCollegeSite:
    university: str
    college: str
    college_type: str
    homepage: str
    province: str = ""
    tags: list[str] = field(default_factory=list)
    note: str = ""
    homepage_ok: bool | None = None

    @property
    def region(self) -> str:
        from institutions_data import PROVINCE_TO_REGION
        return PROVINCE_TO_REGION.get(self.province, "其他")


def _row(university, college, ctype, homepage, note="") -> OfficialCollegeSite:
    return OfficialCollegeSite(
        university=university,
        college=college,
        college_type=ctype,
        homepage=homepage.rstrip("/"),
        province=PROVINCE_BY_UNI.get(university, ""),
        tags=TAGS_BY_UNI.get(university, []),
        note=note,
    )


# (university, college, type, homepage, note)
_RAW: list[tuple] = [
    ("北京大学", "外国语学院", "foreign_lang", "https://sfl.pku.edu.cn", ""),
    ("北京大学", "法学院", "law", "https://law.pku.edu.cn", ""),
    ("中国人民大学", "外国语学院", "foreign_lang", "https://fl.ruc.edu.cn", ""),
    ("中国人民大学", "法学院", "law", "https://law.ruc.edu.cn", ""),
    ("清华大学", "外国语言文学系", "foreign_lang", "https://www.dfll.tsinghua.edu.cn", ""),
    ("清华大学", "法学院", "law", "https://www.law.tsinghua.edu.cn", ""),
    ("北京航空航天大学", "外国语学院", "foreign_lang", "https://sfl.buaa.edu.cn", ""),
    ("北京航空航天大学", "法学院", "law", "https://law.buaa.edu.cn", ""),
    ("北京理工大学", "外国语学院", "foreign_lang", "https://sfl.bit.edu.cn", ""),
    ("北京理工大学", "法学院", "law", "https://law.bit.edu.cn", ""),
    ("中国农业大学", "人文与发展学院", "foreign_lang", "https://cohd.cau.edu.cn", "外语、法学均隶属"),
    ("中国农业大学", "人文与发展学院", "law", "https://cohd.cau.edu.cn", "外语、法学均隶属"),
    ("北京师范大学", "外国语言文学学院", "foreign_lang", "https://sfl.bnu.edu.cn", ""),
    ("北京师范大学", "法学院", "law", "https://law.bnu.edu.cn", ""),
    ("中央民族大学", "外国语学院", "foreign_lang", "https://sfl.muc.edu.cn", ""),
    ("中央民族大学", "法学院", "law", "https://law.muc.edu.cn", ""),
    ("北京交通大学", "语言与传播学院", "foreign_lang", "https://sfs.bjtu.edu.cn", ""),
    ("北京交通大学", "法学院", "law", "https://law.bjtu.edu.cn", ""),
    ("北京工业大学", "外国语学院", "foreign_lang", "https://sfl.bjut.edu.cn", ""),
    ("北京工业大学", "文法学部", "law", "https://wenfa.bjut.edu.cn", ""),
    ("北京科技大学", "外国语学院", "foreign_lang", "https://sfl.ustb.edu.cn", ""),
    ("北京科技大学", "文法学院", "law", "https://wenfa.ustb.edu.cn", ""),
    ("北京化工大学", "外国语学院", "foreign_lang", "https://sfl.buct.edu.cn", ""),
    ("北京化工大学", "文法学院", "law", "https://wfxy.buct.edu.cn", ""),
    ("北京邮电大学", "人文学院", "foreign_lang", "https://rwxy.bupt.edu.cn", "外语、法学均隶属"),
    ("北京邮电大学", "人文学院", "law", "https://rwxy.bupt.edu.cn", "外语、法学均隶属"),
    ("北京林业大学", "外语学院", "foreign_lang", "https://waiyu.bjfu.edu.cn", ""),
    ("北京林业大学", "人文社会科学学院", "law", "https://renwen.bjfu.edu.cn", ""),
    ("北京协和医学院", "人文学院", "foreign_lang", "https://renwen.pumc.edu.cn", "仅公共外语教学"),
    ("北京中医药大学", "人文学院", "foreign_lang", "https://renwen.bucm.edu.cn", "医学英语等"),
    ("北京中医药大学", "人文学院", "law", "https://renwen.bucm.edu.cn", "医药卫生法学"),
    ("北京外国语大学", "英语学院", "foreign_lang", "https://sei.bfsu.edu.cn", ""),
    ("北京外国语大学", "法学院", "law", "https://law.bfsu.edu.cn", ""),
    ("中国传媒大学", "外国语言文化学院", "foreign_lang", "https://sfl.cuc.edu.cn", ""),
    ("中国传媒大学", "法律系", "law", "https://law.cuc.edu.cn", ""),
    ("中央财经大学", "外国语学院", "foreign_lang", "https://sfl.cufe.edu.cn", ""),
    ("中央财经大学", "法学院", "law", "https://law.cufe.edu.cn", ""),
    ("对外经济贸易大学", "外语学院", "foreign_lang", "https://sfs.uibe.edu.cn", ""),
    ("对外经济贸易大学", "法学院", "law", "https://law.uibe.edu.cn", ""),
    ("北京体育大学", "国际体育组织学院", "foreign_lang", "https://ios.bsu.edu.cn", ""),
    ("中国政法大学", "外国语学院", "foreign_lang", "https://wyxy.cupl.edu.cn", ""),
    ("中国政法大学", "法学院", "law", "https://law.cupl.edu.cn", ""),
    ("华北电力大学", "外国语学院", "foreign_lang", "https://sfl.ncepu.edu.cn", ""),
    ("华北电力大学", "人文与社会科学学院", "law", "https://rwxy.ncepu.edu.cn", ""),
    ("中国矿业大学（北京）", "文法学院", "foreign_lang", "https://wenfa.cumtb.edu.cn", "外语、法学均隶属"),
    ("中国矿业大学（北京）", "文法学院", "law", "https://wenfa.cumtb.edu.cn", "外语、法学均隶属"),
    ("中国石油大学（北京）", "外国语学院", "foreign_lang", "https://sfl.cup.edu.cn", ""),
    ("中国地质大学（北京）", "外国语学院", "foreign_lang", "https://wyxy.cugb.edu.cn", ""),
    ("中国地质大学（北京）", "经济管理学院", "law", "https://sem.cugb.edu.cn", "法学隶属"),
    ("中国科学院大学", "外语系", "foreign_lang", "https://sfs.ucas.ac.cn", ""),
    ("中国科学院大学", "公共政策与管理学院", "law", "https://sppm.ucas.ac.cn", "法律系隶属"),
    ("首都师范大学", "外国语学院", "foreign_lang", "https://wyxy.cnu.edu.cn", ""),
    ("首都师范大学", "政法学院", "law", "https://zfxy.cnu.edu.cn", ""),
    ("外交学院", "英语系", "foreign_lang", "https://english.cfau.edu.cn", ""),
    ("外交学院", "国际法系", "law", "https://law.cfau.edu.cn", ""),
    ("中国人民公安大学", "法学院", "law", "https://law.ppsuc.edu.cn", ""),
    ("南开大学", "外国语学院", "foreign_lang", "https://sfl.nankai.edu.cn", ""),
    ("南开大学", "法学院", "law", "https://law.nankai.edu.cn", ""),
    ("天津大学", "外国语学院", "foreign_lang", "https://sfl.tju.edu.cn", ""),
    ("天津大学", "法学院", "law", "https://law.tju.edu.cn", ""),
    ("天津医科大学", "医学人文学院", "foreign_lang", "https://rwxy.tmu.edu.cn", "医学英语"),
    ("天津工业大学", "外国语学院", "foreign_lang", "https://sfl.tiangong.edu.cn", ""),
    ("天津工业大学", "法学院", "law", "https://law.tiangong.edu.cn", ""),
    ("河北工业大学", "外国语学院", "foreign_lang", "https://sfl.hebut.edu.cn", ""),
    ("河北工业大学", "人文与法律学院", "law", "https://wenfa.hebut.edu.cn", ""),
    ("山西大学", "外国语学院", "foreign_lang", "https://sfl.sxu.edu.cn", ""),
    ("山西大学", "法学院", "law", "https://law.sxu.edu.cn", ""),
    ("太原理工大学", "外国语学院", "foreign_lang", "https://wyxy.tyut.edu.cn", ""),
    ("太原理工大学", "政法学院", "law", "https://law.tyut.edu.cn", ""),
    ("内蒙古大学", "外国语学院", "foreign_lang", "https://wgyxy.imu.edu.cn", ""),
    ("内蒙古大学", "法学院", "law", "https://law.imu.edu.cn", ""),
    ("辽宁大学", "外国语学院", "foreign_lang", "https://sfl.lnu.edu.cn", ""),
    ("辽宁大学", "法学院", "law", "https://law.lnu.edu.cn", ""),
    ("大连理工大学", "外国语学院", "foreign_lang", "https://sfl.dlut.edu.cn", ""),
    ("大连理工大学", "人文与社会科学学部", "law", "https://renwen.dlut.edu.cn", "法律系隶属"),
    ("东北大学", "外国语学院", "foreign_lang", "https://sfl.neu.edu.cn", ""),
    ("东北大学", "文法学院", "law", "https://wenfa.neu.edu.cn", ""),
    ("大连海事大学", "外国语学院", "foreign_lang", "https://sfl.dlmu.edu.cn", ""),
    ("大连海事大学", "法学院", "law", "https://law.dlmu.edu.cn", ""),
    ("吉林大学", "外国语学院", "foreign_lang", "https://foreign.jlu.edu.cn", ""),
    ("吉林大学", "法学院", "law", "https://law.jlu.edu.cn", ""),
    ("延边大学", "外国语学院", "foreign_lang", "https://wyxy.ybu.edu.cn", ""),
    ("延边大学", "法学院", "law", "https://law.ybu.edu.cn", ""),
    ("东北师范大学", "外国语学院", "foreign_lang", "https://wyxy.nenu.edu.cn", ""),
    ("东北师范大学", "政法学院", "law", "https://zf.nenu.edu.cn", ""),
    ("哈尔滨工业大学", "外国语学院", "foreign_lang", "https://sfl.hit.edu.cn", ""),
    ("哈尔滨工业大学", "法学院", "law", "https://law.hit.edu.cn", ""),
    ("哈尔滨工程大学", "外国语学院", "foreign_lang", "https://sfl.hrbeu.edu.cn", ""),
    ("哈尔滨工程大学", "人文社会科学学院", "law", "https://rwsk.hrbeu.edu.cn", ""),
    ("东北林业大学", "外国语学院", "foreign_lang", "https://wyxy.nefu.edu.cn", ""),
    ("东北林业大学", "文法学院", "law", "https://wenfa.nefu.edu.cn", ""),
    ("东北农业大学", "国际文化教育学院", "foreign_lang", "https://ic.neau.edu.cn", ""),
    ("复旦大学", "外国语言文学学院", "foreign_lang", "https://dfll.fudan.edu.cn", ""),
    ("复旦大学", "法学院", "law", "https://law.fudan.edu.cn", ""),
    ("同济大学", "外国语学院", "foreign_lang", "https://sfl.tongji.edu.cn", ""),
    ("同济大学", "法学院", "law", "https://law.tongji.edu.cn", ""),
    ("上海交通大学", "外国语学院", "foreign_lang", "https://sfl.sjtu.edu.cn", ""),
    ("上海交通大学", "凯原法学院", "law", "https://law.sjtu.edu.cn", ""),
    ("华东师范大学", "外语学院", "foreign_lang", "https://wyxy.ecnu.edu.cn", ""),
    ("华东师范大学", "法学院", "law", "https://law.ecnu.edu.cn", ""),
    ("华东理工大学", "外国语学院", "foreign_lang", "https://sfl.ecust.edu.cn", ""),
    ("华东理工大学", "法学院", "law", "https://law.ecust.edu.cn", ""),
    ("东华大学", "外语学院", "foreign_lang", "https://sfl.dhu.edu.cn", ""),
    ("东华大学", "人文学院", "law", "https://renwen.dhu.edu.cn", ""),
    ("上海财经大学", "外国语学院", "foreign_lang", "https://sfl.shufe.edu.cn", ""),
    ("上海财经大学", "法学院", "law", "https://law.shufe.edu.cn", ""),
    ("上海大学", "外国语学院", "foreign_lang", "https://sfl.shu.edu.cn", ""),
    ("上海大学", "法学院", "law", "https://law.shu.edu.cn", ""),
    ("上海外国语大学", "英语学院", "foreign_lang", "https://sis.shisu.edu.cn", ""),
    ("上海外国语大学", "法学院", "law", "https://law.shisu.edu.cn", ""),
    ("上海海洋大学", "外国语学院", "foreign_lang", "https://wyxy.shou.edu.cn", ""),
    ("上海海洋大学", "海洋文化与法律学院", "law", "https://wenfa.shou.edu.cn", ""),
    ("南京大学", "外国语学院", "foreign_lang", "https://wyx.nju.edu.cn", ""),
    ("南京大学", "法学院", "law", "https://law.nju.edu.cn", ""),
    ("东南大学", "外国语学院", "foreign_lang", "https://sfl.seu.edu.cn", ""),
    ("东南大学", "法学院", "law", "https://law.seu.edu.cn", ""),
    ("苏州大学", "外国语学院", "foreign_lang", "https://sfl.suda.edu.cn", ""),
    ("苏州大学", "王健法学院", "law", "https://law.suda.edu.cn", ""),
    ("南京航空航天大学", "外国语学院", "foreign_lang", "https://cfl.nuaa.edu.cn", ""),
    ("南京航空航天大学", "人文与社会科学学院", "law", "https://rwxy.nuaa.edu.cn", ""),
    ("南京理工大学", "外国语学院", "foreign_lang", "https://wyxy.njust.edu.cn", ""),
    ("南京理工大学", "知识产权学院", "law", "https://ip.njust.edu.cn", "含法学专业"),
    ("中国矿业大学", "外国语言文化学院", "foreign_lang", "https://sfl.cumt.edu.cn", ""),
    ("中国矿业大学", "公共管理学院", "law", "https://cllp.cumt.edu.cn", "法学隶属"),
    ("河海大学", "外国语学院", "foreign_lang", "https://wyxy.hhu.edu.cn", ""),
    ("河海大学", "法学院", "law", "https://law.hhu.edu.cn", ""),
    ("江南大学", "外国语学院", "foreign_lang", "https://wyxy.jiangnan.edu.cn", ""),
    ("江南大学", "法学院", "law", "https://law.jiangnan.edu.cn", ""),
    ("南京农业大学", "外国语学院", "foreign_lang", "https://sfl.njau.edu.cn", ""),
    ("南京农业大学", "人文与社会发展学院", "law", "https://rwxy.njau.edu.cn", ""),
    ("中国药科大学", "外国语学院", "foreign_lang", "https://sfl.cpu.edu.cn", ""),
    ("南京师范大学", "外国语学院", "foreign_lang", "https://wyxy.njnu.edu.cn", ""),
    ("南京师范大学", "法学院", "law", "https://law.njnu.edu.cn", ""),
    ("南京邮电大学", "外国语学院", "foreign_lang", "https://sfl.njupt.edu.cn", ""),
    ("南京林业大学", "外国语学院", "foreign_lang", "https://sfl.njfu.edu.cn", ""),
    ("南京林业大学", "人文社会科学学院", "law", "https://wenfa.njfu.edu.cn", ""),
    ("南京信息工程大学", "文学院", "foreign_lang", "https://renwen.nuist.edu.cn", "外语隶属"),
    ("南京医科大学", "外国语学院", "foreign_lang", "https://yxwy.njmu.edu.cn", ""),
    ("浙江大学", "外国语言文化与国际交流学院", "foreign_lang", "https://sfl.zju.edu.cn", ""),
    ("浙江大学", "光华法学院", "law", "https://law.zju.edu.cn", ""),
    ("宁波大学", "外国语学院", "foreign_lang", "https://wyxy.nbu.edu.cn", ""),
    ("宁波大学", "法学院", "law", "https://law.nbu.edu.cn", ""),
    ("安徽大学", "外语学院", "foreign_lang", "https://sfl.ahu.edu.cn", ""),
    ("安徽大学", "法学院", "law", "https://law.ahu.edu.cn", ""),
    ("中国科学技术大学", "外语系", "foreign_lang", "https://sfs.ustc.edu.cn", ""),
    ("中国科学技术大学", "公共事务学院", "law", "https://sppm.ustc.edu.cn", "含法学"),
    ("合肥工业大学", "外国语学院", "foreign_lang", "https://sfl.hfut.edu.cn", ""),
    ("合肥工业大学", "文法学院", "law", "https://wenfa.hfut.edu.cn", ""),
    ("厦门大学", "外文学院", "foreign_lang", "https://sfl.xmu.edu.cn", ""),
    ("厦门大学", "法学院", "law", "https://law.xmu.edu.cn", ""),
    ("福州大学", "外国语学院", "foreign_lang", "https://sfl.fzu.edu.cn", ""),
    ("福州大学", "法学院", "law", "https://law.fzu.edu.cn", ""),
    ("南昌大学", "外国语学院", "foreign_lang", "https://wyxy.ncu.edu.cn", ""),
    ("南昌大学", "法学院", "law", "https://law.ncu.edu.cn", ""),
    ("山东大学", "外国语学院", "foreign_lang", "https://www.sfl.sdu.edu.cn", ""),
    ("山东大学", "法学院", "law", "https://law.sdu.edu.cn", ""),
    ("中国海洋大学", "外国语学院", "foreign_lang", "https://sfl.ouc.edu.cn", ""),
    ("中国海洋大学", "法学院", "law", "https://law.ouc.edu.cn", ""),
    ("中国石油大学（华东）", "外国语学院", "foreign_lang", "https://wyxy.upc.edu.cn", ""),
    ("中国石油大学（华东）", "文法学院", "law", "https://wenfa.upc.edu.cn", ""),
    ("郑州大学", "外国语与国际关系学院", "foreign_lang", "https://www.sfl.zzu.edu.cn", ""),
    ("郑州大学", "法学院", "law", "https://law.zzu.edu.cn", ""),
    ("河南大学", "外语学院", "foreign_lang", "https://wyxy.henu.edu.cn", ""),
    ("河南大学", "法学院", "law", "https://law.henu.edu.cn", ""),
    ("武汉大学", "外国语言文学学院", "foreign_lang", "https://sfl.whu.edu.cn", ""),
    ("武汉大学", "法学院", "law", "https://law.whu.edu.cn", ""),
    ("华中科技大学", "外国语学院", "foreign_lang", "https://sfl.hust.edu.cn", ""),
    ("华中科技大学", "法学院", "law", "https://law.hust.edu.cn", ""),
    ("武汉理工大学", "外国语学院", "foreign_lang", "https://sfl.whut.edu.cn", ""),
    ("武汉理工大学", "法学与人文社会学院", "law", "https://wwhy.whut.edu.cn", ""),
    ("华中农业大学", "外国语学院", "foreign_lang", "https://wyxy.hzau.edu.cn", ""),
    ("华中农业大学", "文法学院", "law", "https://wenfa.hzau.edu.cn", ""),
    ("华中师范大学", "外国语学院", "foreign_lang", "https://wyxy.ccnu.edu.cn", ""),
    ("华中师范大学", "法学院", "law", "https://law.ccnu.edu.cn", ""),
    ("中南财经政法大学", "外国语学院", "foreign_lang", "https://sfl.zuel.edu.cn", ""),
    ("中南财经政法大学", "法学院", "law", "https://law.zuel.edu.cn", ""),
    ("中国地质大学（武汉）", "外国语学院", "foreign_lang", "https://wyxy.cug.edu.cn", ""),
    ("中国地质大学（武汉）", "公共管理学院", "law", "https://ggxy.cug.edu.cn", "法学隶属"),
    ("湖南大学", "外国语学院", "foreign_lang", "https://wyxy.hnu.edu.cn", ""),
    ("湖南大学", "法学院", "law", "https://law.hnu.edu.cn", ""),
    ("中南大学", "外国语学院", "foreign_lang", "https://sfl.csu.edu.cn", ""),
    ("中南大学", "法学院", "law", "https://law.csu.edu.cn", ""),
    ("湘潭大学", "外国语学院", "foreign_lang", "https://wyxy.xtu.edu.cn", ""),
    ("湘潭大学", "法学院", "law", "https://law.xtu.edu.cn", ""),
    ("湖南师范大学", "外国语学院", "foreign_lang", "https://wyxy.hunnu.edu.cn", ""),
    ("湖南师范大学", "法学院", "law", "https://law.hunnu.edu.cn", ""),
    ("中山大学", "外国语学院", "foreign_lang", "https://sfl.sysu.edu.cn", ""),
    ("中山大学", "法学院", "law", "https://law.sysu.edu.cn", ""),
    ("华南理工大学", "外国语学院", "foreign_lang", "https://sfl.scut.edu.cn", ""),
    ("华南理工大学", "法学院", "law", "https://law.scut.edu.cn", ""),
    ("暨南大学", "外国语学院", "foreign_lang", "https://sfl.jnu.edu.cn", ""),
    ("暨南大学", "法学院", "law", "https://law.jnu.edu.cn", ""),
    ("广州中医药大学", "外国语学院", "foreign_lang", "https://wyxy.gzucm.edu.cn", ""),
    ("华南农业大学", "外国语学院", "foreign_lang", "https://sfl.scau.edu.cn", ""),
    ("华南农业大学", "人文与法学学院", "law", "https://renwen.scau.edu.cn", ""),
    ("华南师范大学", "外国语言文化学院", "foreign_lang", "https://sfs.scnu.edu.cn", ""),
    ("华南师范大学", "法学院", "law", "https://law.scnu.edu.cn", ""),
    ("广西大学", "外国语学院", "foreign_lang", "https://wyxy.gxu.edu.cn", ""),
    ("广西大学", "法学院", "law", "https://law.gxu.edu.cn", ""),
    ("海南大学", "外国语学院", "foreign_lang", "https://sfl.hainanu.edu.cn", ""),
    ("海南大学", "法学院", "law", "https://law.hainanu.edu.cn", ""),
    ("四川大学", "外国语学院", "foreign_lang", "https://flc.scu.edu.cn", ""),
    ("四川大学", "法学院", "law", "https://law.scu.edu.cn", ""),
    ("电子科技大学", "外国语学院", "foreign_lang", "https://sfl.uestc.edu.cn", ""),
    ("西南交通大学", "外国语学院", "foreign_lang", "https://sfl.swjtu.edu.cn", ""),
    ("西南交通大学", "法学院", "law", "https://law.swjtu.edu.cn", ""),
    ("西南石油大学", "外国语学院", "foreign_lang", "https://sfl.swpu.edu.cn", ""),
    ("西南石油大学", "法学院", "law", "https://law.swpu.edu.cn", ""),
    ("成都理工大学", "外国语学院", "foreign_lang", "https://wyxy.cdut.edu.cn", ""),
    ("成都理工大学", "法学院", "law", "https://law.cdut.edu.cn", ""),
    ("四川农业大学", "人文学院", "foreign_lang", "https://rwxy.sicau.edu.cn", "外语隶属"),
    ("四川农业大学", "法学院", "law", "https://law.sicau.edu.cn", ""),
    ("成都中医药大学", "外语学院", "foreign_lang", "https://wyxy.cdutcm.edu.cn", ""),
    ("西南财经大学", "经贸外语学院", "foreign_lang", "https://jmwy.swufe.edu.cn", ""),
    ("西南财经大学", "法学院", "law", "https://law.swufe.edu.cn", ""),
    ("重庆大学", "外国语学院", "foreign_lang", "https://sfl.cqu.edu.cn", ""),
    ("重庆大学", "法学院", "law", "https://law.cqu.edu.cn", ""),
    ("西南大学", "外国语学院", "foreign_lang", "https://wyxy.swu.edu.cn", ""),
    ("西南大学", "法学院", "law", "https://law.swu.edu.cn", ""),
    ("贵州大学", "外国语学院", "foreign_lang", "https://wyxy.gzu.edu.cn", ""),
    ("贵州大学", "法学院", "law", "https://law.gzu.edu.cn", ""),
    ("云南大学", "外国语学院", "foreign_lang", "https://wyxy.ynu.edu.cn", ""),
    ("云南大学", "法学院", "law", "https://law.ynu.edu.cn", ""),
    ("西藏大学", "旅游与外语学院", "foreign_lang", "https://lywy.utibet.edu.cn", ""),
    ("西藏大学", "政法学院", "law", "https://zf.utibet.edu.cn", ""),
    ("西安交通大学", "外国语学院", "foreign_lang", "https://sfl.xjtu.edu.cn", ""),
    ("西安交通大学", "法学院", "law", "https://law.xjtu.edu.cn", ""),
    ("西北工业大学", "外国语学院", "foreign_lang", "https://wyxy.nwpu.edu.cn", ""),
    ("西北工业大学", "公共政策与管理学院", "law", "https://rwjj.nwpu.edu.cn", "法学隶属"),
    ("西北农林科技大学", "外语系", "foreign_lang", "https://wyx.nwafu.edu.cn", ""),
    ("西北农林科技大学", "人文社会发展学院", "law", "https://rwxy.nwafu.edu.cn", "法学隶属"),
    ("西安电子科技大学", "外国语学院", "foreign_lang", "https://sfl.xidian.edu.cn", ""),
    ("长安大学", "外国语学院", "foreign_lang", "https://sfl.chd.edu.cn", ""),
    ("长安大学", "人文学院", "law", "https://rwxy.chd.edu.cn", "法学隶属"),
    ("西北大学", "外国语学院", "foreign_lang", "https://wyxy.nwu.edu.cn", ""),
    ("西北大学", "法学院", "law", "https://law.nwu.edu.cn", ""),
    ("陕西师范大学", "外国语学院", "foreign_lang", "https://wyxy.snnu.edu.cn", ""),
    ("陕西师范大学", "哲学与政府管理学院", "law", "https://zfxy.snnu.edu.cn", "法学隶属"),
    ("兰州大学", "外国语学院", "foreign_lang", "https://sfl.lzu.edu.cn", ""),
    ("兰州大学", "法学院", "law", "https://law.lzu.edu.cn", ""),
    ("宁夏大学", "外国语学院", "foreign_lang", "https://wyxy.nxu.edu.cn", ""),
    ("宁夏大学", "法学院", "law", "https://law.nxu.edu.cn", ""),
    ("新疆大学", "外国语学院", "foreign_lang", "https://sfl.xju.edu.cn", ""),
    ("新疆大学", "法学院", "law", "https://law.xju.edu.cn", ""),
    ("石河子大学", "外国语学院", "foreign_lang", "https://sfl.shzu.edu.cn", ""),
    ("石河子大学", "法学院", "law", "https://law.shzu.edu.cn", ""),
]

OFFICIAL_COLLEGE_SITES: list[OfficialCollegeSite] = [_row(*r) for r in _RAW]

NEWS_PATH_CANDIDATES = [
    "/xwzx/tzgg/index.htm",
    "/xwtz/tzgg/index.htm",
    "/index/tzgg.htm",
    "/882/list.htm",
    "/tzgg/list.htm",
    "/Data/List/tzgg",
    "/news/tzgg/index.htm",
]


def derive_news_urls(homepage: str) -> list[str]:
    base = homepage.rstrip("/")
    return [base + p for p in NEWS_PATH_CANDIDATES]


def site_key(university: str, college: str, college_type: str) -> tuple[str, str, str]:
    return (university, college, college_type)


def get_site(university: str, college: str, college_type: str) -> OfficialCollegeSite | None:
    for s in OFFICIAL_COLLEGE_SITES:
        if s.university == university and s.college == college and s.college_type == college_type:
            return s
    return None
